### ISSUE TITLE
EL8 Support

### ISSUE THREAD

**Issue by bodgit** [bodgit/puppet-zfs#13]
- [x] CentOS 8 vagrant box
- [x] EPEL Puppet module support
- [x] ZFS packages available

**Comment by cf-sewe** [comment]
I tried the current release version and it doesnt work yet with CentOS 8.
Actually the repo is added to the system repo config and then the yum/dnf update fail because it cannot find the repo (as expected).

```
repo: downloading from remote: zfs
ZFS on Linux for EL8 - dkms                                                                                                                                                                                                   222  B/s | 304  B     00:01
Cannot download 'http://download.zfsonlinux.org/epel/8/x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried.
```
This would work: `http://download.zfsonlinux.org/epel/8.0/x86_64/repodata/repomd.xml`
The ZOL documentation specifies to use `http://download.zfsonlinux.org/epel/zfs-release.el8_0.noarch.rpm`. Would it make sense to use it for bodgit-zfs or does it have advantage to setup the repos manually?

Here are the OS-facts from my CentOS system:
```
package_provider: dnf
osfamily: RedHat
os: {u'name': u'CentOS', u'family': u'RedHat', u'selinux': {u'enabled': False}, u'hardware': u'x86_64', u'architecture': u'x86_64', u'release': {u'major': u'8', u'full': u'8.0.1905', u'minor': u'0'}}
operatingsystemrelease: 8.0.1905
operatingsystemmajrelease: 8
operatingsystem: CentOS
```

Update: I just found the dependency to puppet-yum, and that that one also does not support RHEL8 distro yet. So I guess I have to manually setup ZFS for now.

**Comment by bodgit** [comment]
I have the changes locally to get this working, however I think you need the EPEL repository available to be able to install the DKMS package(s) and I'm currently waiting on https://github.com/stahnma/puppet-module-epel/issues/61 so I can run the acceptance tests.

**Comment by bodgit** [comment]
Finally, the epel module has been released with CentOS 8 support so I can finally progress this.
